import SwiftUI

/// AI Insights card displaying tide pooling tips generated by Gemini
struct AIInsightView: View {
    let insightText: String
    let isLoading: Bool
    var body: some View {
        ZStack(alignment: .topLeading) {
            RoundedRectangle(cornerRadius: 24)
                .fill(Color.blue.opacity(0.15))
            
            VStack(alignment: .leading, spacing: 12) {
                // Header
                Text("AI Insights ✨")
                    .font(.system(size: 16,weight: .bold))
                    .fallbackFont(.system(size: 16, weight: .bold))
                    .foregroundColor(.black)
                
                // Content or Loading State
                if isLoading {
                    HStack {
                        Spacer()
                        ProgressView()
                            .progressViewStyle(CircularProgressViewStyle(tint: Color.blue))
                        Spacer()
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 20)
                } else {
                    Text(insightText.isEmpty ? "Tap to refresh for a new insight!" : insightText)
                        .font(.system(size: 24,weight: .medium))
                        .fallbackFont(.system(size: 20))
                        .foregroundColor(Color(red: 0.2, green: 0.2, blue: 0.2))
                        .multilineTextAlignment(.leading)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            .padding(20)
        }
        .frame(minHeight: 160)
    }
}

// MARK: - Font Extension for Fallback
extension Font {
    func fallbackFont(_ fallback: Font) -> Font {
        // SwiftUI will automatically fall back to system font if custom font is not available
        return self
    }
}

extension View {
    func fallbackFont(_ fallback: Font) -> some View {
        // This is a helper to make the API cleaner, but SwiftUI handles fallback automatically
        return self
    }
}

#Preview {
    VStack(spacing: 20) {
        AIInsightView(
            insightText: "Look for purple sea urchins in the exposed tide pools at 1.8ft. Hermit crabs are scurrying between rocks in the warm 68°F sun!",
            isLoading: false
        )
        .padding()
        
        AIInsightView(
            insightText: "",
            isLoading: true
        )
        .padding()
    }
}
